-- =============================================================================
-- MIGRACION: usuarios y registro de movimientos
-- Ejecutar una sola vez en bases creadas antes de que existiera el inicio de sesión
-- con usuarios. Se puede ejecutar varias veces: lo que ya existe no se toca.
-- Crea el usuario inicial admin / prueba (cambiar la contraseña desde la app).
-- =============================================================================

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE TBL_USUARIO (
            USU_ID              NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            USU_LOGIN           VARCHAR2(30)    NOT NULL UNIQUE,
            USU_HASH            VARCHAR2(100)   NOT NULL,
            USU_SAL             VARCHAR2(50)    NOT NULL,
            USU_ROL             VARCHAR2(20)    NOT NULL,
            PER_ID              NUMBER,
            USU_ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
            USU_ULTIMO_INGRESO  DATE,
            CONSTRAINT CK_USUARIO_ROL CHECK (USU_ROL IN ('Administrador', 'Empleado')),
            CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (PER_ID) REFERENCES TBL_PERSONA(PER_ID) ON DELETE SET NULL
        )]';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;  -- -955: la tabla ya existe
END;
/

BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE TBL_MOVIMIENTO (
            MOV_ID      NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            USU_ID      NUMBER,
            MOV_FECHA   DATE            DEFAULT SYSDATE NOT NULL,
            MOV_ACCION  VARCHAR2(60)    NOT NULL,
            MOV_DETALLE VARCHAR2(500),
            CONSTRAINT FK_MOVIMIENTO_USUARIO FOREIGN KEY (USU_ID) REFERENCES TBL_USUARIO(USU_ID) ON DELETE SET NULL
        )]';
    EXECUTE IMMEDIATE 'CREATE INDEX IX_MOVIMIENTO_FECHA ON TBL_MOVIMIENTO (MOV_FECHA)';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

INSERT INTO TBL_USUARIO (USU_LOGIN, USU_HASH, USU_SAL, USU_ROL)
SELECT 'admin', 'nkhgKTXFe3rOhaqDRm5koU9hsplo/Np79/lxeHOA4mY=', 'sm1wuzSGfi5SSI7f7jg10Q==', 'Administrador' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM TBL_USUARIO WHERE USU_LOGIN = 'admin');

COMMIT;
