-- =============================================================================
-- MIGRACION: sincronizar secuencias e identidades con los datos existentes
-- Ejecutar una sola vez en bases creadas con versiones anteriores de schema.sql
-- (requiere Oracle 18c o superior). Se puede ejecutar varias veces sin problema.
--
-- Corrige:
--  - "ORA-00001 ... TBL_CLIENTE (CLI_ID)" al crear el primer cliente desde la app
--  - "ORA-00001 ... TBL_PERSONA (PER_ID)" al crear un cliente despues de una persona
-- =============================================================================

DECLARE
    v_siguiente NUMBER;
BEGIN
    SELECT NVL(MAX(PER_ID), 0) + 1 INTO v_siguiente FROM TBL_PERSONA;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PERSONA RESTART START WITH ' || v_siguiente;

    SELECT NVL(MAX(PRO_ID), 0) + 1 INTO v_siguiente FROM TBL_PRODUCTO;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_PRODUCTO RESTART START WITH ' || v_siguiente;

    SELECT NVL(MAX(REC_ID_RECLAMO), 0) + 1 INTO v_siguiente FROM TBL_RECLAMO;
    EXECUTE IMMEDIATE 'ALTER SEQUENCE SEQ_RECLAMO RESTART START WITH ' || v_siguiente;
END;
/

-- START WITH LIMIT VALUE: la identidad continua despues del mayor ID existente
ALTER TABLE TBL_CLIENTE MODIFY (CLI_ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE TBL_VENDEDOR MODIFY (VEN_ID GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
